// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Context;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241226184523_addAmenity")]
    partial class addAmenity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VillaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7e62742-ec8d-4d52-abd0-52cf234eae56"),
                            Name = "Private Pool",
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Id = new Guid("24b3f9f0-f184-423d-9ae6-c2247131f55e"),
                            Name = "Microwave",
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Id = new Guid("b88ace2e-2235-4969-a858-91f640d11d43"),
                            Name = "Private Balcony",
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Id = new Guid("0545955d-fd70-45bf-9220-9641e2378437"),
                            Name = "1 king bed and 1 sofa bed",
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Id = new Guid("2f25775c-b773-4570-9617-06544d279ebc"),
                            Name = "Private Plunge Pool",
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Id = new Guid("8744551e-3a8d-4dd6-b8d1-449a09a8700d"),
                            Name = "Microwave and Mini Refrigerator",
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Id = new Guid("95c6ea25-596d-456a-ae9e-2cb3f8106047"),
                            Name = "Private Balcony",
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Id = new Guid("f4ceb631-cded-4516-ac2b-08a479cc42eb"),
                            Name = "king bed or 2 double beds",
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Id = new Guid("e8c50b20-6013-4ff7-9557-d7f54f77457e"),
                            Name = "Private Pool",
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        },
                        new
                        {
                            Id = new Guid("9c246920-3da3-4ecf-b2e5-a30b51b27cc0"),
                            Name = "Jacuzzi",
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        },
                        new
                        {
                            Id = new Guid("740b18ee-cd55-43d6-96a1-98e41ad7cf70"),
                            Name = "Private Balcony",
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e"),
                            CreatedDate = new DateTime(2024, 12, 27, 1, 45, 21, 229, DateTimeKind.Local).AddTicks(6143),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae"),
                            CreatedDate = new DateTime(2024, 12, 27, 1, 45, 21, 229, DateTimeKind.Local).AddTicks(6179),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a"),
                            CreatedDate = new DateTime(2024, 12, 27, 1, 45, 21, 229, DateTimeKind.Local).AddTicks(6183),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VillaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
