// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Context;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241224140727_addVillaNumber")]
    partial class addVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e"),
                            CreatedDate = new DateTime(2024, 12, 24, 21, 7, 25, 99, DateTimeKind.Local).AddTicks(444),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae"),
                            CreatedDate = new DateTime(2024, 12, 24, 21, 7, 25, 99, DateTimeKind.Local).AddTicks(472),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a"),
                            CreatedDate = new DateTime(2024, 12, 24, 21, 7, 25, 99, DateTimeKind.Local).AddTicks(476),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VillaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaId = new Guid("22c2f426-2256-4db1-b5b9-881f13b91b7e")
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaId = new Guid("6b359322-86e1-43c4-9eac-57bf9054d1ae")
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaId = new Guid("4e93d429-8b79-4313-91e9-0a2b9c2c5d6a")
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
